### PR TITLE
Create env variable for deployment

### LINKED ISSUE #115: Set up environment variables for deployment
Estimate: 6 hours?

### PR DESCRIPTION
**Pull request by Baagi**
## Description

Now we can use env file to set which hosturl we want to make api calls to. 
Since we only call to APIs on the frontend, the changes here are mostly replacing the `localhost` urls in our api calls. 

## Code review 
Code review only this commit: https://github.com/MaggieYang57/CSC308-TeamB/pull/125/commits/e91e700b0bacfbb11ac880e97f7e81a568982a21

## Instructions

If you want to use the local backend, use the following steps:
1. Create `.env` file inside the `/frontend/` dir.
2. Add the following to the `.env` file: `REACT_APP_BACKEND_HOST_URL=http://localhost:3001`

If you want to use the live site backend, use the following steps:
1. Create `.env` file inside the `/frontend/` dir.
2. Add the following to the `.env` file: `REACT_APP_BACKEND_HOST_URL=https://slo-hikes-backend.herokuapp.com`
Screen Shot 2021-05-12 at 12 40 45 PM

Note: It will require you to run `npm start` after changing the env variables.

## After merging

1. Set this env in heroku config: `REACT_APP_BACKEND_HOST_URL=https://slo-hikes-backend.herokuapp.com`
2. Make your `.env` files in `/frontend/` folder on your machine, otherwise it will not work. 

closes #115

### CODE REVIEW

**Review by MaggieYang57 — COMMENTED** [review]
Hi Bat! First off, thank you for such a nice PR description and having a clear summary with precise instructions in utilizing the .env variables!

Other than some tiny styling adjustments, it seems to me that the only change was adding dotenv to the files with API calls, which is why I'm writing this as one general comment. I think it was a good idea to make a backendHostURL const to call in each fetch command - it makes the overall code a little more clean and easier to read. Everything looks good to me!

**Review by srietkerk — COMMENTED** [review]
Everything looks good to me, Bat! 

I just have a question about the back-ticks that are used for the URL now instead of quotes. Are the back-ticks used to denote a sort of path?

**Comment by srietkerk** [comment]
Also, I agree with Maggie, the description that you have attached to the process looks awesome and is super straight forward, thanks!!

**Comment by Baagi** [comment]
> I just have a question about the back-ticks that are used for the URL now instead of quotes. Are the back-ticks used to denote a sort of path?

I think they are called template literals: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Basically another way of concatenating strings together.

**Pull request merged**
